// Organized categories and tagged all utilities with consistent, simple tag attributes.
import {
  Brain,
  ImageIcon,
  Link2,
  MessageCircle,
  Palette,
  PenTool,
  QrCode,
  Type,
  Lock,
  FileText,
  Trophy,
  Compass,
  Calculator,
  FileText as PdfIcon,
  Globe,
} from 'lucide-react';

export const tools = [
  {
    icon: Brain,
    title: 'Quizzable',
    description:
      'Create interactive quizzes for your audience. Export to JSON or share link to your audience instantly.',
    href: '/quiz',
    color: '#18cb83ff',
    tag: 'Assessment',
    id: 'quizzable',
    category: 'Engagement',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: PenTool,
    title: 'Creator Hub',
    description:
      'The ultimate social creator hub to make posts, with translation, grammar check, AI assistance and more.',
    href: '/composer',
    color: '#0ebae1ff',
    tag: 'Social Post',
    category: 'Engagement',
    id: 'composer',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: MessageCircle,
    id: 'anonlink',
    category: 'Engagement',
    title: 'Anonymous Link',
    description:
      'Send and receive anonymous messages with secure end-to-end encryption features.',
    href: '/message',
    color: '#7b8afbff',
    tag: 'Anon Inbox',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Type,
    title: 'Text Editor',
    category: 'Content',
    id: 'editor',
    description:
      'The ultimate offline-first rich text document workspace & note-stacking dashboard with postcard creation and exports.',
    href: '/editor',
    color: '#f622fdff',
    tag: 'Notes & Editor',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: ImageIcon,
    title: 'Image Toolkit',
    category: 'Media',
    description:
      'Premium image editing tools. Edit, convert, compress, and remove backgrounds from images directly in the browser.',
    href: '/image',
    color: '#FFB347',
    tag: 'Image Edit',
    id: 'image',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Globe,
    title: 'Country Directory',
    description:
      'Explore high-fidelity country flags, ISO codes, calling info, languages, currencies, and geographic data with instant modular search.',
    href: '/countries',
    color: '#0ea5e9',
    tag: 'Countries',
    id: 'countries',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Link2,
    title: 'URL Shortener',
    description:
      'More than a link shortener. Generate QR codes and track link health with advanced local analytics.',
    href: '/tools/url-shortener',
    color: '#fe7790ff',
    tag: 'Link Tool',
    id: 'shortener',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: QrCode,
    title: 'QR Code Generator',
    description:
      'Generate WiFi, URL, email, SMS, and vCard QR codes with custom colors and instant download.',
    href: '/tools/qr-code',
    color: '#adff72ff',
    tag: 'QR Code',
    category: 'Utility',
    id: 'qr-code',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Palette,
    title: 'Color Palette',
    description:
      'More color manipulation tools with color generation, extraction, color picker, color randomizer and more.',
    href: '/tools/colors',
    color: '#ea6b89ff',
    tag: 'Color Tool',
    id: 'color-palette',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Lock,
    title: 'Password Generator',
    description:
      'Generate ultra secure random passwords locally to keep your social and business accounts completely protected.',
    href: '/tools/password-gen',
    color: '#00ba7c',
    tag: 'Security',
    id: 'password-gen',
    category: 'Security',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: FileText,
    title: 'Word Counter',
    description:
      'Live lexical analysis tool counting words, chars, density, readability metrics, and speech readability indexes.',
    href: '/tools/word-counter',
    color: '#ff8c42',
    tag: 'Text Tool',
    id: 'word-counter',
    category: 'Content',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Trophy,
    title: 'Tournament Table',
    description:
      'Interactive tournament or league standings table to track points, goals, wins, and draws automatically.',
    href: '/tools/games',
    color: '#bc1888',
    tag: 'Standings',
    id: 'games',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Compass,
    title: 'IP Locator',
    description:
      'Locate and fetch detailed geospatial coordinates, ISP data, and country information from any input IP.',
    href: '/tools/ip-locator',
    color: '#ff5c7a',
    tag: 'Network',
    id: 'ip-locator',
    category: 'Security',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Calculator,
    title: 'Multi Calculator',
    description:
      'All-in-one calculator with tabs for: Pricing markup, Currency conversion, Unit conversions, Percentage, BMI, Loan/EMI, Age, and Tip calculations.',
    href: '/tools/calculator',
    color: '#1d9bf0',
    tag: 'Calculator',
    id: 'calculator',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Lock,
    title: 'Secure Encryption',
    description:
      'Encrypt and decrypt data using highly secure client-side cryptography algorithms (AES, TripleDES, RC4) and passkeys.',
    href: '/tools/encryption',
    color: '#985cff',
    tag: 'Encryption',
    id: 'encryption',
    category: 'Security',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: PdfIcon,
    title: 'PDF Tool',
    description:
      'Image to PDF, PDF merging/splitting, text-to-pdf, and pdf-to-text conversion tool purely client-side.',
    href: '/tools/pdf',
    color: '#ff3b30',
    tag: 'PDF',
    id: 'pdf-tools',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
];

export const companyData = {
  webDomain: 'https://ping-world.site',
  webEmail: 'pingworld.com@gmail.com',
  launchDate: 'August 1, 2026',
  parentBrandLink: 'https://qal-tech-website',
  parentName: 'Qal Technologies',
  parenNameShort: 'Qal Tech',
  devName: 'Paschal Ngaoka',
  devLink: 'https://wa.me/2349016561308',
  devBrandName: 'PoshCodes',
  devBrandLink: 'https://pascodes-tech.netlify.app',
};
