import {
  Brain,
  ImageIcon,
  Link2,
  MessageCircle,
  Palette,
  PenTool,
  QrCode,
  Type,
  Lock,
  FileText,
  Trophy,
  Compass,
  Globe,
  Calculator,
  FileCode,
  FileText as PdfIcon
} from "lucide-react";

export const tools = [
  {
    icon: Brain,
    title: 'Quizzable',
    description:
      'Create interactive quizzes for your audience. Export to JSON or share link to your audience instantly.',
    href: '/quiz',
    color: '#18cb83ff',
    tag: 'Powerful',
    id: 'quizzable',
    category: 'Engagement',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: PenTool,
    title: 'Creator Hub',
    description:
      'The ultimate social creator hub to make posts, with translation, grammar check, AI assistance and more.',
    href: '/composer',
    color: '#0ebae1ff',
    tag: 'Creative',
    category: 'Engagement',
    id: 'composer',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: MessageCircle,
    id: 'anonlink',
    category: 'Communication',
    title: 'Anonymous Link',
    description:
      'Send and receive anonymous messages with secure end-to-end encryption features.',
    href: '/message',
    color: '#7b8afbff',
    tag: 'Popular',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Type,
    title: 'Text Editor',
    category: 'Content',
    id: 'editor',
    description:
      'Top notch all-in-one text editor with post card generation and export options.',
    href: '/editor',
    color: '#f622fdff',
    tag: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: ImageIcon,
    title: 'Image Toolkit',
    description:
      'Premium image editing tools. Edit, convert, compress, and remove backgrounds from images directly in the browser.',
    href: '/image',
    color: '#FFB347',
    tag: 'New',
    id: 'image',
    category: 'Media',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Link2,
    title: 'URL Shortener',
    description:
      'More than a link shortener. Generate QR codes and track link health with advanced local analytics.',
    href: '/tools/url-shortener',
    color: '#fe7790ff',
    tag: 'Utility',
    id: 'shortener',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: QrCode,
    title: 'QR Code Generator',
    description:
      'More than a shortener. Generate QR codes and track link health with advanced local analytics.',
    href: '/tools/qr-code',
    color: '#adff72ff',
    tag: 'Utility',
    category: 'Utility',
    id: 'qr-code',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Palette,
    title: 'Color Palette',
    description:
      'More color manipulation tools with color generation, extraction, color picker, color randomizer and more.',
    href: '/tools/colors',
    color: '#ea6b89ff',
    tag: 'Utility',
    id: 'color-palette',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Lock,
    title: 'Password Generator',
    description:
      'Generate ultra secure random passwords locally to keep your social and business accounts completely protected.',
    href: '/tools/password-gen',
    color: '#00ba7c',
    tag: 'Secure',
    id: 'password-gen',
    category: 'Security',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: FileText,
    title: 'Word Counter',
    description:
      'Live lexical analysis tool counting words, chars, density, readability metrics, and speech readability indexes.',
    href: '/tools/word-counter',
    color: '#ff8c42',
    tag: 'Utility',
    id: 'word-counter',
    category: 'Content',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Trophy,
    title: 'Games Standings',
    description:
      'Interactive tournament or league standings table to track points, goals, wins, and draws automatically.',
    href: '/tools/games',
    color: '#bc1888',
    tag: 'New',
    id: 'games',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Compass,
    title: 'IP Locator',
    description:
      'Locate and fetch detailed geospatial coordinates, ISP data, and country information from any input IP.',
    href: '/tools/ip-locator',
    color: '#ff5c7a',
    tag: 'Network',
    id: 'ip-locator',
    category: 'Security',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Calculator,
    title: 'Multi Calculator',
    description:
      'Perform weight/volume unit conversions, complex percentages, interest pricing, and real-time live currency conversion.',
    href: '/tools/calculator',
    color: '#1d9bf0',
    tag: 'Finance',
    id: 'calculator',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: FileCode,
    title: 'Offline Notes',
    description:
      'Local-first secure offline text notes with custom categorizations, stacking, search capability, and sync option.',
    href: '/tools/notes',
    color: '#22c985',
    tag: 'Utility',
    id: 'notes',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: Lock,
    title: 'Secure Encryption',
    description:
      'Encrypt and decrypt data using highly secure client-side cryptography algorithms (AES, TripleDES, RC4) and passkeys.',
    href: '/tools/encryption',
    color: '#985cff',
    tag: 'Secure',
    id: 'encryption',
    category: 'Security',
    version: { v: '1.0', s: 'Stable' },
  },
  {
    icon: PdfIcon,
    title: 'PDF Tool Studio',
    description:
      'Image to PDF, PDF merging/splitting, text-to-pdf, and pdf-to-text conversion tool purely client-side.',
    href: '/tools/pdf',
    color: '#ff3b30',
    tag: 'New',
    id: 'pdf-tools',
    category: 'Utility',
    version: { v: '1.0', s: 'Stable' },
  }
];
