
import PublicQuizTaker from '@/components/quiz/PublicQuizTaker';
import {HybridStorage} from '@/lib/storage-utils';
import type { Metadata } from 'next';

interface QuizParams {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: QuizParams): Promise<Metadata> {
  const {id} = await params;
  try{
    const timeout = new Promise<null>((res) => setTimeout(() => res(null), 1500));
    const quiz = await Promise.race([
      HybridStorage.getQuiz(id, 'title, description').catch(() => null),
      timeout,
    ]);

    if (quiz) {
      const title = `${quiz.title} | Assessment - Ping World`;
      const description = quiz.description || 'Take the assessment, generated by the Ping World platform.';
      return {
        title,
        description,
        keywords: [
          'Quiz Taker',
          'Quiz',
          'quizzable',
          'Ping World',
          'assessment',
          'survey',
          'exams',
          'questions',
          'q&a'
        ],
        openGraph: {
          title,
          description,
          type: 'website',
          siteName: 'Ping World',
        },
        twitter: {
          card: 'summary_large_image',
          title,
          description,
        },
      };
    }
  } catch (e) {
    console.warn('Failed to load quiz metadata', e);
  }

  return {
    title: 'Assessment',
    description: 'Take the assessment, generated by the Ping World platform',
    openGraph: {
      title: 'Assessment',
      description: 'Take the assessment, generated by the Ping World platform',
    },
  };
}

export default function QuizIDPage() {
  return <PublicQuizTaker />;
}
