export interface Country {
  name: string;
  code: string;
  flag: string;
  language: string;
  capital: string;
  currency: string;
  population: string;
  ethnicity: string;
  region: 'Americas' | 'Europe' | 'Asia' | 'Africa' | 'Oceania';
  timezone: string;
  callingCode: string;
  tld: string;
  areaSqKm: string;
}

export const countriesDb: Country[] = [
  // --- AFRICA ---
  {
    name: 'Nigeria',
    code: 'NG',
    flag: '🇳🇬',
    language: 'English, Hausa, Igbo, Yoruba',
    capital: 'Abuja',
    currency: 'NGN',
    population: '206M',
    ethnicity: 'Hausa, Yoruba, Igbo, Fulani',
    region: 'Africa',
    timezone: 'UTC+1',
    callingCode: '+234',
    tld: '.ng',
    areaSqKm: '923,768',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    flag: '🇿🇦',
    language: 'Zulu, Xhosa, Afrikaans, English',
    capital: 'Pretoria',
    currency: 'ZAR',
    population: '59M',
    ethnicity: 'Black, Coloured, White, Indian',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+27',
    tld: '.za',
    areaSqKm: '1,219,090',
  },
  {
    name: 'Egypt',
    code: 'EG',
    flag: '🇪🇬',
    language: 'Arabic',
    capital: 'Cairo',
    currency: 'EGP',
    population: '102M',
    ethnicity: 'Egyptian, Nubian',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+20',
    tld: '.eg',
    areaSqKm: '1,002,450',
  },
  {
    name: 'Kenya',
    code: 'KE',
    flag: '🇰🇪',
    language: 'Swahili, English',
    capital: 'Nairobi',
    currency: 'KES',
    population: '53M',
    ethnicity: 'Kikuyu, Luhya, Luo, Kalenjin',
    region: 'Africa',
    timezone: 'UTC+3',
    callingCode: '+254',
    tld: '.ke',
    areaSqKm: '580,367',
  },
  {
    name: 'Ghana',
    code: 'GH',
    flag: '🇬🇭',
    language: 'English, Akan',
    capital: 'Accra',
    currency: 'GHS',
    population: '31M',
    ethnicity: 'Akan, Mole-Dagbon, Ewe',
    region: 'Africa',
    timezone: 'UTC+0',
    callingCode: '+233',
    tld: '.gh',
    areaSqKm: '238,533',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    flag: '🇪🇹',
    language: 'Amharic',
    capital: 'Addis Ababa',
    currency: 'ETB',
    population: '115M',
    ethnicity: 'Oromo, Amhara, Tigrayan',
    region: 'Africa',
    timezone: 'UTC+3',
    callingCode: '+251',
    tld: '.et',
    areaSqKm: '1,104,300',
  },
  {
    name: 'Morocco',
    code: 'MA',
    flag: '🇲🇦',
    language: 'Arabic, Berber',
    capital: 'Rabat',
    currency: 'MAD',
    population: '36M',
    ethnicity: 'Arab-Berber',
    region: 'Africa',
    timezone: 'UTC+1',
    callingCode: '+212',
    tld: '.ma',
    areaSqKm: '446,550',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    flag: '🇩🇿',
    language: 'Arabic, Berber',
    capital: 'Algiers',
    currency: 'DZD',
    population: '43M',
    ethnicity: 'Arab-Berber',
    region: 'Africa',
    timezone: 'UTC+1',
    callingCode: '+213',
    tld: '.dz',
    areaSqKm: '2,381,741',
  },
  {
    name: 'Uganda',
    code: 'UG',
    flag: '🇺🇬',
    language: 'English, Swahili',
    capital: 'Kampala',
    currency: 'UGX',
    population: '45M',
    ethnicity: 'Baganda, Banyankole, Basoga',
    region: 'Africa',
    timezone: 'UTC+3',
    callingCode: '+256',
    tld: '.ug',
    areaSqKm: '241,038',
  },
  {
    name: 'Angola',
    code: 'AO',
    flag: '🇦🇴',
    language: 'Portuguese',
    capital: 'Luanda',
    currency: 'AOA',
    population: '32M',
    ethnicity: 'Ovimbundu, Ambundu, Bakongo',
    region: 'Africa',
    timezone: 'UTC+1',
    callingCode: '+244',
    tld: '.ao',
    areaSqKm: '1,246,700',
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    flag: '🇹🇿',
    language: 'Swahili, English',
    capital: 'Dodoma',
    currency: 'TZS',
    population: '60M',
    ethnicity: 'Sukuma, Chagga, Haya',
    region: 'Africa',
    timezone: 'UTC+3',
    callingCode: '+255',
    tld: '.tz',
    areaSqKm: '945,087',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    flag: '🇨🇲',
    language: 'French, English',
    capital: 'Yaoundé',
    currency: 'XAF',
    population: '26M',
    ethnicity: 'Cameroon Highlanders, Equatorial Bantu',
    region: 'Africa',
    timezone: 'UTC+1',
    callingCode: '+237',
    tld: '.cm',
    areaSqKm: '475,442',
  },
  {
    name: 'Ivory Coast',
    code: 'CI',
    flag: '🇨🇮',
    language: 'French',
    capital: 'Yamoussoukro',
    currency: 'XOF',
    population: '26M',
    ethnicity: 'Akan, Gur, Northern Mande',
    region: 'Africa',
    timezone: 'UTC+0',
    callingCode: '+225',
    tld: '.ci',
    areaSqKm: '322,463',
  },
  {
    name: 'Senegal',
    code: 'SN',
    flag: '🇸🇳',
    language: 'French, Wolof',
    capital: 'Dakar',
    currency: 'XOF',
    population: '17M',
    ethnicity: 'Wolof, Fula, Serer',
    region: 'Africa',
    timezone: 'UTC+0',
    callingCode: '+221',
    tld: '.sn',
    areaSqKm: '196,722',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    flag: '🇿🇼',
    language: 'Shona, Ndebele, English',
    capital: 'Harare',
    currency: 'ZWL',
    population: '15M',
    ethnicity: 'Shona, Ndebele',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+263',
    tld: '.zw',
    areaSqKm: '390,757',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    flag: '🇿🇲',
    language: 'English, Bemba, Nyanja',
    capital: 'Lusaka',
    currency: 'ZMW',
    population: '18M',
    ethnicity: 'Bemba, Tonga, Chewa',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+260',
    tld: '.zm',
    areaSqKm: '752,618',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    flag: '🇷🇼',
    language: 'Kinyarwanda, French, English',
    capital: 'Kigali',
    currency: 'RWF',
    population: '13M',
    ethnicity: 'Hutu, Tutsi, Twa',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+250',
    tld: '.rw',
    areaSqKm: '26,338',
  },
  {
    name: 'Libya',
    code: 'LY',
    flag: '🇱🇾',
    language: 'Arabic',
    capital: 'Tripoli',
    currency: 'LYD',
    population: '7M',
    ethnicity: 'Arab, Berber',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+218',
    tld: '.ly',
    areaSqKm: '1,759,540',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    flag: '🇹🇳',
    language: 'Arabic, Berber',
    capital: 'Tunis',
    currency: 'TND',
    population: '11M',
    ethnicity: 'Arab, Berber',
    region: 'Africa',
    timezone: 'UTC+1',
    callingCode: '+216',
    tld: '.tn',
    areaSqKm: '163,610',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    flag: '🇲🇿',
    language: 'Portuguese',
    capital: 'Maputo',
    currency: 'MZN',
    population: '31M',
    ethnicity: 'Makhuwa, Tsonga, Lomwe',
    region: 'Africa',
    timezone: 'UTC+2',
    callingCode: '+258',
    tld: '.mz',
    areaSqKm: '801,590',
  },

  // --- AMERICAS ---
  {
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    language: 'English',
    capital: 'Washington, D.C.',
    currency: 'USD',
    population: '331M',
    ethnicity: 'White, Hispanic, Black, Asian',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+1',
    tld: '.us',
    areaSqKm: '9,833,517',
  },
  {
    name: 'Canada',
    code: 'CA',
    flag: '🇨🇦',
    language: 'English, French',
    capital: 'Ottawa',
    currency: 'CAD',
    population: '38M',
    ethnicity: 'Canadian, English, French, Scottish',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+1',
    tld: '.ca',
    areaSqKm: '9,984,670',
  },
  {
    name: 'Brazil',
    code: 'BR',
    flag: '🇧🇷',
    language: 'Portuguese',
    capital: 'Brasília',
    currency: 'BRL',
    population: '212M',
    ethnicity: 'White, Mixed (Pardo), Black, East Asian',
    region: 'Americas',
    timezone: 'UTC-3',
    callingCode: '+55',
    tld: '.br',
    areaSqKm: '8,515,767',
  },
  {
    name: 'Mexico',
    code: 'MX',
    flag: '🇲🇽',
    language: 'Spanish',
    capital: 'Mexico City',
    currency: 'MXN',
    population: '128M',
    ethnicity: 'Mestizo, Indigenous, White',
    region: 'Americas',
    timezone: 'UTC-6',
    callingCode: '+52',
    tld: '.mx',
    areaSqKm: '1,964,375',
  },
  {
    name: 'Argentina',
    code: 'AR',
    flag: '🇦🇷',
    language: 'Spanish',
    capital: 'Buenos Aires',
    currency: 'ARS',
    population: '45M',
    ethnicity: 'European descent, Mestizo',
    region: 'Americas',
    timezone: 'UTC-3',
    callingCode: '+54',
    tld: '.ar',
    areaSqKm: '2,780,400',
  },
  {
    name: 'Colombia',
    code: 'CO',
    flag: '🇨🇴',
    language: 'Spanish',
    capital: 'Bogotá',
    currency: 'COP',
    population: '50M',
    ethnicity: 'Mestizo, White, Afro-Colombian',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+57',
    tld: '.co',
    areaSqKm: '1,141,748',
  },
  {
    name: 'Peru',
    code: 'PE',
    flag: '🇵🇪',
    language: 'Spanish, Quechua',
    capital: 'Lima',
    currency: 'PEN',
    population: '32M',
    ethnicity: 'Mestizo, Amerindian, White',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+51',
    tld: '.pe',
    areaSqKm: '1,285,216',
  },
  {
    name: 'Chile',
    code: 'CL',
    flag: '🇨🇱',
    language: 'Spanish',
    capital: 'Santiago',
    currency: 'CLP',
    population: '19M',
    ethnicity: 'White, non-Indigenous, Mapuche',
    region: 'Americas',
    timezone: 'UTC-3',
    callingCode: '+56',
    tld: '.cl',
    areaSqKm: '756,102',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    flag: '🇻🇪',
    language: 'Spanish',
    capital: 'Caracas',
    currency: 'VES',
    population: '28M',
    ethnicity: 'Mestizo, Spanish, Italian, Portuguese',
    region: 'Americas',
    timezone: 'UTC-4',
    callingCode: '+58',
    tld: '.ve',
    areaSqKm: '916,445',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    flag: '🇪🇨',
    language: 'Spanish, Kichwa',
    capital: 'Quito',
    currency: 'USD',
    population: '17M',
    ethnicity: 'Mestizo, Amerindian, Afro-Ecuadorian',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+593',
    tld: '.ec',
    areaSqKm: '283,561',
  },
  {
    name: 'Cuba',
    code: 'CU',
    flag: '🇨🇺',
    language: 'Spanish',
    capital: 'Havana',
    currency: 'CUP',
    population: '11M',
    ethnicity: 'White, Mulato, Black',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+53',
    tld: '.cu',
    areaSqKm: '109,884',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    flag: '🇧🇴',
    language: 'Spanish, Quechua, Aymara',
    capital: 'Sucre',
    currency: 'BOB',
    population: '11M',
    ethnicity: 'Mestizo, Indigenous, White',
    region: 'Americas',
    timezone: 'UTC-4',
    callingCode: '+591',
    tld: '.bo',
    areaSqKm: '1,098,581',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    flag: '🇵🇾',
    language: 'Spanish, Guaraní',
    capital: 'Asunción',
    currency: 'PYG',
    population: '7M',
    ethnicity: 'Mestizo, Indigenous',
    region: 'Americas',
    timezone: 'UTC-4',
    callingCode: '+595',
    tld: '.py',
    areaSqKm: '406,752',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    flag: '🇺🇾',
    language: 'Spanish',
    capital: 'Montevideo',
    currency: 'UYU',
    population: '3.5M',
    ethnicity: 'White, Mestizo, Black',
    region: 'Americas',
    timezone: 'UTC-3',
    callingCode: '+598',
    tld: '.uy',
    areaSqKm: '176,215',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    flag: '🇯🇲',
    language: 'English, Jamaican Patois',
    capital: 'Kingston',
    currency: 'JMD',
    population: '3M',
    ethnicity: 'Black, Mixed, Indian',
    region: 'Americas',
    timezone: 'UTC-5',
    callingCode: '+1-876',
    tld: '.jm',
    areaSqKm: '10,991',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    flag: '🇨🇷',
    language: 'Spanish',
    capital: 'San José',
    currency: 'CRC',
    population: '5M',
    ethnicity: 'White/Mestizo, Mulato, Indigenous',
    region: 'Americas',
    timezone: 'UTC-6',
    callingCode: '+506',
    tld: '.cr',
    areaSqKm: '51,100',
  },

  // --- ASIA ---
  {
    name: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    language: 'Japanese',
    capital: 'Tokyo',
    currency: 'JPY',
    population: '125M',
    ethnicity: 'Japanese, Korean, Chinese',
    region: 'Asia',
    timezone: 'UTC+9',
    callingCode: '+81',
    tld: '.jp',
    areaSqKm: '377,975',
  },
  {
    name: 'India',
    code: 'IN',
    flag: '🇮🇳',
    language: 'Hindi, English',
    capital: 'New Delhi',
    currency: 'INR',
    population: '1.4B',
    ethnicity: 'Indo-Aryan, Dravidian, Mongoloid',
    region: 'Asia',
    timezone: 'UTC+5:30',
    callingCode: '+91',
    tld: '.in',
    areaSqKm: '3,287,263',
  },
  {
    name: 'South Korea',
    code: 'KR',
    flag: '🇰🇷',
    language: 'Korean',
    capital: 'Seoul',
    currency: 'KRW',
    population: '51M',
    ethnicity: 'Korean',
    region: 'Asia',
    timezone: 'UTC+9',
    callingCode: '+82',
    tld: '.kr',
    areaSqKm: '100,210',
  },
  {
    name: 'China',
    code: 'CN',
    flag: '🇨🇳',
    language: 'Mandarin',
    capital: 'Beijing',
    currency: 'CNY',
    population: '1.4B',
    ethnicity: 'Han Chinese, Zhuang, Hui',
    region: 'Asia',
    timezone: 'UTC+8',
    callingCode: '+86',
    tld: '.cn',
    areaSqKm: '9,596,960',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    flag: '🇮🇩',
    language: 'Indonesian',
    capital: 'Jakarta',
    currency: 'IDR',
    population: '273M',
    ethnicity: 'Javanese, Sundanese, Malay',
    region: 'Asia',
    timezone: 'UTC+7',
    callingCode: '+62',
    tld: '.id',
    areaSqKm: '1,904,569',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    flag: '🇵🇰',
    language: 'Urdu, English',
    capital: 'Islamabad',
    currency: 'PKR',
    population: '220M',
    ethnicity: 'Punjabi, Pashtun, Sindhi, Saraiki',
    region: 'Asia',
    timezone: 'UTC+5',
    callingCode: '+92',
    tld: '.pk',
    areaSqKm: '881,913',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    flag: '🇧🇩',
    language: 'Bengali',
    capital: 'Dhaka',
    currency: 'BDT',
    population: '164M',
    ethnicity: 'Bengali',
    region: 'Asia',
    timezone: 'UTC+6',
    callingCode: '+880',
    tld: '.bd',
    areaSqKm: '147,570',
  },
  {
    name: 'Philippines',
    code: 'PH',
    flag: '🇵🇭',
    language: 'Filipino, English',
    capital: 'Manila',
    currency: 'PHP',
    population: '109M',
    ethnicity: 'Tagalog, Cebuano, Ilocano',
    region: 'Asia',
    timezone: 'UTC+8',
    callingCode: '+63',
    tld: '.ph',
    areaSqKm: '343,448',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    flag: '🇻🇳',
    language: 'Vietnamese',
    capital: 'Hanoi',
    currency: 'VND',
    population: '97M',
    ethnicity: 'Kinh (Viet), Tay, Thai',
    region: 'Asia',
    timezone: 'UTC+7',
    callingCode: '+84',
    tld: '.vn',
    areaSqKm: '331,212',
  },
  {
    name: 'Turkey',
    code: 'TR',
    flag: '🇹🇷',
    language: 'Turkish',
    capital: 'Ankara',
    currency: 'TRY',
    population: '84M',
    ethnicity: 'Turkish, Kurdish',
    region: 'Asia',
    timezone: 'UTC+3',
    callingCode: '+90',
    tld: '.tr',
    areaSqKm: '783,356',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    flag: '🇸🇦',
    language: 'Arabic',
    capital: 'Riyadh',
    currency: 'SAR',
    population: '35M',
    ethnicity: 'Arab',
    region: 'Asia',
    timezone: 'UTC+3',
    callingCode: '+966',
    tld: '.sa',
    areaSqKm: '2,149,690',
  },
  {
    name: 'Iran',
    code: 'IR',
    flag: '🇮🇷',
    language: 'Persian',
    capital: 'Tehran',
    currency: 'IRR',
    population: '84M',
    ethnicity: 'Persian, Azerbaijani, Kurd',
    region: 'Asia',
    timezone: 'UTC+3:30',
    callingCode: '+98',
    tld: '.ir',
    areaSqKm: '1,648,195',
  },
  {
    name: 'Israel',
    code: 'IL',
    flag: '🇮🇱',
    language: 'Hebrew, Arabic',
    capital: 'Jerusalem',
    currency: 'ILS',
    population: '9M',
    ethnicity: 'Jewish, Arab',
    region: 'Asia',
    timezone: 'UTC+2',
    callingCode: '+972',
    tld: '.il',
    areaSqKm: '20,770',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    language: 'Arabic',
    capital: 'Abu Dhabi',
    currency: 'AED',
    population: '10M',
    ethnicity: 'Emirati, South Asian, Arab',
    region: 'Asia',
    timezone: 'UTC+4',
    callingCode: '+971',
    tld: '.ae',
    areaSqKm: '83,600',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    flag: '🇲🇾',
    language: 'Malay',
    capital: 'Kuala Lumpur',
    currency: 'MYR',
    population: '32M',
    ethnicity: 'Malay, Chinese, Indian',
    region: 'Asia',
    timezone: 'UTC+8',
    callingCode: '+60',
    tld: '.my',
    areaSqKm: '329,847',
  },
  {
    name: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    language: 'Thai',
    capital: 'Bangkok',
    currency: 'THB',
    population: '70M',
    ethnicity: 'Thai, Chinese, Malay',
    region: 'Asia',
    timezone: 'UTC+7',
    callingCode: '+66',
    tld: '.th',
    areaSqKm: '513,120',
  },
  {
    name: 'Singapore',
    code: 'SG',
    flag: '🇸🇬',
    language: 'English, Malay, Mandarin, Tamil',
    capital: 'Singapore',
    currency: 'SGD',
    population: '5.9M',
    ethnicity: 'Chinese, Malay, Indian',
    region: 'Asia',
    timezone: 'UTC+8',
    callingCode: '+65',
    tld: '.sg',
    areaSqKm: '728',
  },
  {
    name: 'Myanmar',
    code: 'MM',
    flag: '🇲🇲',
    language: 'Burmese',
    capital: 'Naypyidaw',
    currency: 'MMK',
    population: '54M',
    ethnicity: 'Bamar, Shan, Karen',
    region: 'Asia',
    timezone: 'UTC+6:30',
    callingCode: '+95',
    tld: '.mm',
    areaSqKm: '676,578',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    flag: '🇱🇰',
    language: 'Sinhala, Tamil',
    capital: 'Sri Jayawardenepura Kotte',
    currency: 'LKR',
    population: '22M',
    ethnicity: 'Sinhalese, Tamil, Moor',
    region: 'Asia',
    timezone: 'UTC+5:30',
    callingCode: '+94',
    tld: '.lk',
    areaSqKm: '65,610',
  },
  {
    name: 'Nepal',
    code: 'NP',
    flag: '🇳🇵',
    language: 'Nepali',
    capital: 'Kathmandu',
    currency: 'NPR',
    population: '29M',
    ethnicity: 'Chhettri, Brahman-Hill, Magar',
    region: 'Asia',
    timezone: 'UTC+5:45',
    callingCode: '+977',
    tld: '.np',
    areaSqKm: '147,181',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    flag: '🇰🇿',
    language: 'Kazakh, Russian',
    capital: 'Astana',
    currency: 'KZT',
    population: '19M',
    ethnicity: 'Kazakh, Russian, Uzbek',
    region: 'Asia',
    timezone: 'UTC+6',
    callingCode: '+7',
    tld: '.kz',
    areaSqKm: '2,724,900',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    flag: '🇮🇶',
    language: 'Arabic, Kurdish',
    capital: 'Baghdad',
    currency: 'IQD',
    population: '40M',
    ethnicity: 'Arab, Kurdish, Turkoman',
    region: 'Asia',
    timezone: 'UTC+3',
    callingCode: '+964',
    tld: '.iq',
    areaSqKm: '438,317',
  },
  {
    name: 'Qatar',
    code: 'QA',
    flag: '🇶🇦',
    language: 'Arabic',
    capital: 'Doha',
    currency: 'QAR',
    population: '2.9M',
    ethnicity: 'Qatari, South Asian, Arab',
    region: 'Asia',
    timezone: 'UTC+3',
    callingCode: '+974',
    tld: '.qa',
    areaSqKm: '11,586',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    flag: '🇰🇼',
    language: 'Arabic',
    capital: 'Kuwait City',
    currency: 'KWD',
    population: '4.3M',
    ethnicity: 'Kuwaiti, South Asian, Arab',
    region: 'Asia',
    timezone: 'UTC+3',
    callingCode: '+965',
    tld: '.kw',
    areaSqKm: '17,818',
  },

  // --- EUROPE ---
  {
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    language: 'English',
    capital: 'London',
    currency: 'GBP',
    population: '67M',
    ethnicity: 'White, Asian, Black, Mixed',
    region: 'Europe',
    timezone: 'UTC+0',
    callingCode: '+44',
    tld: '.uk',
    areaSqKm: '242,495',
  },
  {
    name: 'Germany',
    code: 'DE',
    flag: '🇩🇪',
    language: 'German',
    capital: 'Berlin',
    currency: 'EUR',
    population: '83M',
    ethnicity: 'German, Turkish, Polish',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+49',
    tld: '.de',
    areaSqKm: '357,114',
  },
  {
    name: 'France',
    code: 'FR',
    flag: '🇫🇷',
    language: 'French',
    capital: 'Paris',
    currency: 'EUR',
    population: '67M',
    ethnicity: 'French, North African, Italian',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+33',
    tld: '.fr',
    areaSqKm: '643,801',
  },
  {
    name: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    language: 'Italian',
    capital: 'Rome',
    currency: 'EUR',
    population: '60M',
    ethnicity: 'Italian, German, French',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+39',
    tld: '.it',
    areaSqKm: '301,340',
  },
  {
    name: 'Spain',
    code: 'ES',
    flag: '🇪🇸',
    language: 'Spanish',
    capital: 'Madrid',
    currency: 'EUR',
    population: '47M',
    ethnicity: 'Spanish, Catalan, Galician',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+34',
    tld: '.es',
    areaSqKm: '505,990',
  },
  {
    name: 'Russia',
    code: 'RU',
    flag: '🇷🇺',
    language: 'Russian',
    capital: 'Moscow',
    currency: 'RUB',
    population: '145M',
    ethnicity: 'Russian, Tatar, Ukrainian',
    region: 'Europe',
    timezone: 'UTC+3',
    callingCode: '+7',
    tld: '.ru',
    areaSqKm: '17,098,242',
  },
  {
    name: 'Poland',
    code: 'PL',
    flag: '🇵🇱',
    language: 'Polish',
    capital: 'Warsaw',
    currency: 'PLN',
    population: '38M',
    ethnicity: 'Polish, Silesian',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+48',
    tld: '.pl',
    areaSqKm: '312,696',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    flag: '🇺🇦',
    language: 'Ukrainian',
    capital: 'Kyiv',
    currency: 'UAH',
    population: '41M',
    ethnicity: 'Ukrainian, Russian',
    region: 'Europe',
    timezone: 'UTC+2',
    callingCode: '+380',
    tld: '.ua',
    areaSqKm: '603,550',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    flag: '🇳🇱',
    language: 'Dutch',
    capital: 'Amsterdam',
    currency: 'EUR',
    population: '17M',
    ethnicity: 'Dutch, Moroccan, Turkish',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+31',
    tld: '.nl',
    areaSqKm: '41,543',
  },
  {
    name: 'Belgium',
    code: 'BE',
    flag: '🇧🇪',
    language: 'Dutch, French, German',
    capital: 'Brussels',
    currency: 'EUR',
    population: '11M',
    ethnicity: 'Flemish, Walloon',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+32',
    tld: '.be',
    areaSqKm: '30,528',
  },
  {
    name: 'Sweden',
    code: 'SE',
    flag: '🇸🇪',
    language: 'Swedish',
    capital: 'Stockholm',
    currency: 'SEK',
    population: '10M',
    ethnicity: 'Swedish, Finnish, Syriac',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+46',
    tld: '.se',
    areaSqKm: '450,295',
  },
  {
    name: 'Norway',
    code: 'NO',
    flag: '🇳🇴',
    language: 'Norwegian',
    capital: 'Oslo',
    currency: 'NOK',
    population: '5.4M',
    ethnicity: 'Norwegian, Sámi',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+47',
    tld: '.no',
    areaSqKm: '385,207',
  },
  {
    name: 'Denmark',
    code: 'DK',
    flag: '🇩🇰',
    language: 'Danish',
    capital: 'Copenhagen',
    currency: 'DKK',
    population: '5.8M',
    ethnicity: 'Scandinavian, Turkish, Lebanese',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+45',
    tld: '.dk',
    areaSqKm: '42,924',
  },
  {
    name: 'Finland',
    code: 'FI',
    flag: '🇫🇮',
    language: 'Finnish, Swedish',
    capital: 'Helsinki',
    currency: 'EUR',
    population: '5.5M',
    ethnicity: 'Finnish, Swedo-Finnish, Sámi',
    region: 'Europe',
    timezone: 'UTC+2',
    callingCode: '+358',
    tld: '.fi',
    areaSqKm: '338,145',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    flag: '🇨🇭',
    language: 'German, French, Italian, Romansh',
    capital: 'Bern',
    currency: 'CHF',
    population: '8.5M',
    ethnicity: 'Swiss German, French, Italian',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+41',
    tld: '.ch',
    areaSqKm: '41,285',
  },
  {
    name: 'Austria',
    code: 'AT',
    flag: '🇦🇹',
    language: 'German',
    capital: 'Vienna',
    currency: 'EUR',
    population: '9M',
    ethnicity: 'Austrian, German, Serbian',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+43',
    tld: '.at',
    areaSqKm: '83,871',
  },
  {
    name: 'Portugal',
    code: 'PT',
    flag: '🇵🇹',
    language: 'Portuguese',
    capital: 'Lisbon',
    currency: 'EUR',
    population: '10M',
    ethnicity: 'Portuguese, Roma, Ukrainian',
    region: 'Europe',
    timezone: 'UTC+0',
    callingCode: '+351',
    tld: '.pt',
    areaSqKm: '92,212',
  },
  {
    name: 'Greece',
    code: 'GR',
    flag: '🇬🇷',
    language: 'Greek',
    capital: 'Athens',
    currency: 'EUR',
    population: '10.7M',
    ethnicity: 'Greek, Albanian',
    region: 'Europe',
    timezone: 'UTC+2',
    callingCode: '+30',
    tld: '.gr',
    areaSqKm: '131,957',
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    flag: '🇨🇿',
    language: 'Czech',
    capital: 'Prague',
    currency: 'CZK',
    population: '10.9M',
    ethnicity: 'Czech, Moravian, Slovak',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+420',
    tld: '.cz',
    areaSqKm: '78,866',
  },
  {
    name: 'Romania',
    code: 'RO',
    flag: '🇷🇴',
    language: 'Romanian',
    capital: 'Bucharest',
    currency: 'RON',
    population: '19M',
    ethnicity: 'Romanian, Hungarian, Roma',
    region: 'Europe',
    timezone: 'UTC+2',
    callingCode: '+40',
    tld: '.ro',
    areaSqKm: '238,397',
  },
  {
    name: 'Hungary',
    code: 'HU',
    flag: '🇭🇺',
    language: 'Hungarian',
    capital: 'Budapest',
    currency: 'HUF',
    population: '9.7M',
    ethnicity: 'Hungarian, Roma, German',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+36',
    tld: '.hu',
    areaSqKm: '93,028',
  },
  {
    name: 'Ireland',
    code: 'IE',
    flag: '🇮🇪',
    language: 'Irish, English',
    capital: 'Dublin',
    currency: 'EUR',
    population: '5M',
    ethnicity: 'Irish, Eastern European, Nigerian',
    region: 'Europe',
    timezone: 'UTC+0',
    callingCode: '+353',
    tld: '.ie',
    areaSqKm: '70,273',
  },
  {
    name: 'Croatia',
    code: 'HR',
    flag: '🇭🇷',
    language: 'Croatian',
    capital: 'Zagreb',
    currency: 'EUR',
    population: '4M',
    ethnicity: 'Croat, Serb, Bosniak',
    region: 'Europe',
    timezone: 'UTC+1',
    callingCode: '+385',
    tld: '.hr',
    areaSqKm: '56,594',
  },

  // --- OCEANIA ---
  {
    name: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    language: 'English',
    capital: 'Canberra',
    currency: 'AUD',
    population: '25M',
    ethnicity: 'Australian, English, Irish, Italian',
    region: 'Oceania',
    timezone: 'UTC+10',
    callingCode: '+61',
    tld: '.au',
    areaSqKm: '7,692,024',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    flag: '🇳🇿',
    language: 'English, Māori',
    capital: 'Wellington',
    currency: 'NZD',
    population: '5M',
    ethnicity: 'European, Māori, Asian, Pacific peoples',
    region: 'Oceania',
    timezone: 'UTC+12',
    callingCode: '+64',
    tld: '.nz',
    areaSqKm: '268,021',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    flag: '🇵🇬',
    language: 'Tok Pisin, English, Hiri Motu',
    capital: 'Port Moresby',
    currency: 'PGK',
    population: '9M',
    ethnicity: 'Melanesian, Papuan, Micronesian',
    region: 'Oceania',
    timezone: 'UTC+10',
    callingCode: '+675',
    tld: '.pg',
    areaSqKm: '462,840',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    flag: '🇫🇯',
    language: 'English, Fijian, Fiji Hindi',
    capital: 'Suva',
    currency: 'FJD',
    population: '896K',
    ethnicity: 'iTaukei, Indo-Fijian',
    region: 'Oceania',
    timezone: 'UTC+12',
    callingCode: '+679',
    tld: '.fj',
    areaSqKm: '18,274',
  },
  {
    name: 'Samoa',
    code: 'WS',
    flag: '🇼🇸',
    language: 'Samoan, English',
    capital: 'Apia',
    currency: 'WST',
    population: '200K',
    ethnicity: 'Samoan, Euronesian',
    region: 'Oceania',
    timezone: 'UTC+13',
    callingCode: '+685',
    tld: '.ws',
    areaSqKm: '2,842',
  },
];

export function searchCountries(query: string): Country[] {
  const clean = query.trim().toLowerCase();
  if (!clean) return countriesDb;
  return countriesDb.filter(
    (c) =>
      c.name.toLowerCase().includes(clean) ||
      c.code.toLowerCase().includes(clean) ||
      c.capital.toLowerCase().includes(clean) ||
      c.language.toLowerCase().includes(clean) ||
      (c.callingCode && c.callingCode.includes(clean)) ||
      (c.tld && c.tld.includes(clean)),
  );
}

export function filterCountriesByRegion(region: string): Country[] {
  if (region === "All") return countriesDb;
  return countriesDb.filter(c => c.region === region);
}

export function getCountryByCode(code: string): Country | undefined {
  return countriesDb.find(c => c.code.toUpperCase() === code.toUpperCase());
}
