
import PublicQuizTaker from '@/components/quiz/PublicQuizTaker';
import {HybridStorage} from '@/lib/storage-utils';
import type { Metadata } from 'next';

interface QuizParams {
  params: Promise<{ id: string }>;
}

export async function generateMetadata ({params}: QuizParams): Promise<Metadata> {
  
  const { id } = await params;
  try {
    const timeout = new Promise<null>((res) => setTimeout(() => res(null), 1500));
    const quiz = await Promise.race([
      HybridStorage.getQuiz(id, 'title, description').catch(() => null),
      timeout,
    ]);

    if (quiz) {
      const title = `${quiz.title} | Assessment with Quizzable`;
      const description = quiz.description || 'Take the assessment, generated by the Quizzable platform.';
      return {
        title,
        description,
        keywords: [
          'Quiz Taker',
          'Quiz',
          'quizzable',
          'Ping World',
          'assessment',
          'survey',
        ],
        openGraph: {
          title,
          description,
          type: 'website',
          siteName: 'Quizzable',
        },
        twitter: {
          card: 'summary_large_image',
          title,
          description,
        },
      };
    }
  } catch (e) {
    console.warn('Failed to load short-quiz metadata', e);
  }

  return {
    title: 'Assessment with Quizzable',
    description: 'Take the assessment, generated by the Quizzable platform',
    openGraph: {
      title: 'Assessment with Quizzable',
      description: 'Take the assessment, generated by the Quizzable platform',
    },
  };
}

export default function ShortQuizIDPage() {
  return <PublicQuizTaker />;
}
